In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import glob
from PIL import Image

In [2]:
crack = []
files = glob.glob("./image_15/*.jpg")
for i, file in enumerate(files):
        image = Image.open(file)
        image = image.convert("RGB")
        data = np.asarray(image)
        crack.append(data)
crack = np.array(crack)
crack = crack.astype('float32')
crack = crack / 255.0
0.7764706  0.7254902  0.6627451

In [23]:
img = cv2.imread("./image_15/crack_4_2.jpg")
img = img.astype('float32')
img = img / 255.0

In [25]:
img.shape

(15, 15, 3)

In [47]:
img = cv2.imread("./image_256/img_256_4.jpg")

img[:, 128, 0:2] = 0

cv2.imshow("test", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
print(img)

[[[0.18431373 0.1882353  0.24313726]
  [0.22745098 0.23137255 0.28627452]
  [0.25490198 0.26666668 0.32156864]
  [0.33333334 0.35686275 0.40784314]
  [0.47843137 0.5019608  0.5529412 ]
  [0.54509807 0.5764706  0.627451  ]
  [0.5764706  0.6117647  0.6627451 ]
  [0.63529414 0.67058825 0.72156864]
  [0.65882355 0.7058824  0.7529412 ]
  [0.65882355 0.7058824  0.7529412 ]
  [0.65882355 0.7137255  0.7607843 ]
  [0.654902   0.70980394 0.75686276]
  [0.64705884 0.7019608  0.7490196 ]
  [0.64705884 0.7019608  0.7490196 ]
  [0.6509804  0.7058824  0.7529412 ]]

 [[0.16470589 0.16470589 0.21960784]
  [0.20784314 0.21176471 0.26666668]
  [0.24313726 0.24705882 0.3019608 ]
  [0.23921569 0.2509804  0.30588236]
  [0.29803923 0.32156864 0.37254903]
  [0.41960785 0.4509804  0.5019608 ]
  [0.50980395 0.5411765  0.5921569 ]
  [0.5294118  0.5647059  0.6156863 ]
  [0.6313726  0.6666667  0.7176471 ]
  [0.69803923 0.74509805 0.7921569 ]
  [0.6509804  0.69803923 0.74509805]
  [0.65882355 0.7137255  0.7607843 ]

In [ ]:
def scanning(img):
    k_size = 1
    step = 1
    h,w = img.shape[:2]
    x = k_size
    y = k_size
    x_step = step
    y_step = step
    x0 = 0
    y0 = 0
    j = 0
    
    #縦方向の操作を行うループ
    while y + (j * y_step) < h:
        i = 0
        ys = y0 + (j * y_step)
        yf = y + (j * y_step)
        
        #横方向の操作をするループ
        while x + (i * x_step) < w:
            roi = img[ys:yf, x0 + (i * x_step):x + (i * x_step)]
            
            #ここからが領域に対する画像処理
            if roi[0] < 0.34:
                img[]
            #ここまでが領域に対する画像処理
            
            i = i + 1
        j = j + 1
    return 0

In [ ]:
x 

In [14]:
print(crack[5][7][7])

[0.77254903 0.73333335 0.6862745 ]


In [ ]:
dense_size = 2

for j in range(i):
    if crack[j][7][7]
    
        